# Tile mode look for the Windows 3 theme (plain sway commands).
font pango:MS Sans Serif, Noto Sans Bold 8
titlebar_padding 4 2
titlebar_border_thickness 1
default_border normal 3
default_floating_border normal 3

# class                 border  backgr. text    indicator child_border
client.focused          #000000 #000080 #ffffff #000080   #c0c0c0
client.focused_inactive #000000 #ffffff #000000 #c0c0c0   #ffffff
client.unfocused        #000000 #ffffff #000000 #c0c0c0   #ffffff
client.urgent           #000000 #800000 #ffffff #800000   #c0c0c0
