complete -c tilewin-media -f
complete -c tilewin-media -l no-popup -d 'Do not show the popup'
complete -c tilewin-media -n __fish_use_subcommand -a volume -d 'Show or change the volume'
complete -c tilewin-media -n __fish_use_subcommand -a mute -d 'Mute or unmute'
complete -c tilewin-media -n __fish_use_subcommand -a unmute -d 'Unmute'
complete -c tilewin-media -n __fish_use_subcommand -a mic -d 'Mute or unmute the microphone'
complete -c tilewin-media -n __fish_use_subcommand -a brightness -d 'Show or change the brightness'
complete -c tilewin-media -n __fish_use_subcommand -a play -d 'Play or pause music'
complete -c tilewin-media -n __fish_use_subcommand -a next -d 'Next track'
complete -c tilewin-media -n __fish_use_subcommand -a previous -d 'Previous track'
complete -c tilewin-media -n __fish_use_subcommand -a stop -d 'Stop the music'
complete -c tilewin-media -n __fish_use_subcommand -a music -d 'Show what is playing'
complete -c tilewin-media -n __fish_use_subcommand -a help -d 'Show examples'
complete -c tilewin-media -n '__fish_seen_subcommand_from volume brightness' -a 'up down +10 -10 50' -d 'Amount'
complete -c tilewin-media -n '__fish_seen_subcommand_from volume' -a 'mute unmute toggle'
complete -c tilewin-media -n '__fish_seen_subcommand_from mic' -a 'mute unmute toggle'
