# one directory for each screen saver that comes with tileWin
subdir('aurora')
subdir('blank')
subdir('bubbles')
subdir('diggers')
subdir('doomsday')
subdir('flyingwindows')
subdir('gravity')
subdir('matrix')
subdir('maze')
subdir('microslop')
subdir('mystify')
subdir('photos')
subdir('pipes')
subdir('ribbons')
subdir('starfield')
subdir('text3d')
subdir('tiling')
subdir('wordclock')
