
# Tile mode look for the Windows 8 theme (plain sway commands).
font pango:Segoe UI, Noto Sans 9
titlebar_padding 10 7
titlebar_border_thickness 1
default_border normal 2
default_floating_border normal 2

# class                 border  backgr. text    indicator child_border
client.focused          #4f84c0 #6ba5e7 #000000 #2672ec   #6ba5e7
client.focused_inactive #aaaaaa #ebebeb #999999 #aaaaaa   #ebebeb
client.unfocused        #aaaaaa #ebebeb #999999 #aaaaaa   #ebebeb
client.urgent           #c75050 #c75050 #ffffff #c75050   #c75050
