executable(
	'tilewin-settings', [
		'confdoc.c',
		'ipc.c',
		'main.c',
		'page_about.c',
		'page_account.c',
		'page_animations.c',
		'page_apps.c',
		'page_bluetooth.c',
		'page_datetime.c',
		'page_desktop.c',
		'page_keyboard.c',
		'page_launcher.c',
		'page_menus.c',
		'page_mouse.c',
		'page_screen.c',
		'page_screensaver.c',
		'page_sound.c',
		'page_taskbar.c',
		'page_theme.c',
		'page_wallpaper.c',
		'page_window.c',
		'reorder.c',
		'ui.c',
		'widgets.c',
	],
	include_directories: [sway_inc, include_directories('../screensaver')],
	dependencies: [gtk4, dependency('gio-unix-2.0'), jsonc, cairo, gdk_pixbuf, math, rsvg, pango],
	link_with: [lib_savers, lib_sway_common],
	install: true,
)

install_data(
	'../data/tilewin-settings.desktop',
	install_dir: join_paths(datadir, 'applications'),
)
