# Tile mode look for the Windows 1 theme (plain sway commands): its windows
# were tiled in the first place.
font pango:Fixedsys Excelsior, Terminus, DejaVu Sans Mono, Monospace Bold 9
titlebar_padding 4 2
titlebar_border_thickness 1
default_border normal 1
default_floating_border normal 1

# class                 border  backgr. text    indicator child_border
client.focused          #000000 #5555ff #ffffff #5555ff   #000000
client.focused_inactive #000000 #ffffff #000000 #55ffff   #000000
client.unfocused        #000000 #ffffff #000000 #55ffff   #000000
client.urgent           #000000 #ff5555 #ffffff #ff5555   #000000
