# Tile mode look for the Windows 95 theme (plain sway commands).
font pango:Tahoma, MS Sans Serif, Noto Sans Bold 8
titlebar_padding 4 2
titlebar_border_thickness 1
default_border normal 2
default_floating_border normal 2

# class                 border  backgr. text    indicator child_border
client.focused          #000080 #000080 #ffffff #1084d0   #c0c0c0
client.focused_inactive #808080 #808080 #c0c0c0 #808080   #c0c0c0
client.unfocused        #808080 #808080 #c0c0c0 #808080   #c0c0c0
client.urgent           #800000 #800000 #ffffff #800000   #c0c0c0
