#include "emoji.h"

/*
 * The two tabs of the emoji picker that are no emoji: mathematical symbols,
 * and emoticons made of text (ASCII and a few classics that need a little
 * more than ASCII). Each has a name to search it by.
 */

const struct emoji math_symbols[] = {
	// arithmetic
	{ "±", "plus-minus sign" },
	{ "∓", "minus-plus sign" },
	{ "×", "multiplication times sign" },
	{ "÷", "division sign divide" },
	{ "−", "minus sign" },
	{ "·", "middle dot multiply" },
	{ "∘", "ring operator compose" },
	{ "√", "square root radical" },
	{ "∛", "cube root" },
	{ "∜", "fourth root" },
	{ "∝", "proportional to" },
	{ "∞", "infinity" },
	{ "‰", "per mille" },
	{ "°", "degree" },
	{ "′", "prime minute" },
	{ "″", "double prime second" },
	// relations
	{ "≠", "not equal to" },
	{ "≈", "almost equal approximately" },
	{ "≡", "identical to congruent" },
	{ "≢", "not identical to" },
	{ "≅", "approximately equal congruent" },
	{ "∼", "tilde similar" },
	{ "≔", "colon equals defined as" },
	{ "≤", "less than or equal to" },
	{ "≥", "greater than or equal to" },
	{ "≪", "much less than" },
	{ "≫", "much greater than" },
	// calculus and big operators
	{ "∑", "n-ary summation sum sigma" },
	{ "∏", "n-ary product" },
	{ "∫", "integral" },
	{ "∬", "double integral" },
	{ "∭", "triple integral" },
	{ "∮", "contour integral" },
	{ "∂", "partial differential derivative" },
	{ "∇", "nabla del gradient" },
	{ "∆", "increment delta difference" },
	// sets
	{ "∈", "element of in" },
	{ "∉", "not an element of" },
	{ "∋", "contains as member" },
	{ "⊂", "subset of" },
	{ "⊃", "superset of" },
	{ "⊆", "subset of or equal to" },
	{ "⊇", "superset of or equal to" },
	{ "⊄", "not a subset of" },
	{ "∪", "union" },
	{ "∩", "intersection" },
	{ "∅", "empty set" },
	{ "∖", "set minus difference" },
	{ "ℕ", "natural numbers" },
	{ "ℤ", "integers" },
	{ "ℚ", "rational numbers" },
	{ "ℝ", "real numbers" },
	{ "ℂ", "complex numbers" },
	{ "ℵ", "aleph" },
	// logic
	{ "∀", "for all" },
	{ "∃", "there exists" },
	{ "∄", "there does not exist" },
	{ "¬", "not negation" },
	{ "∧", "logical and wedge" },
	{ "∨", "logical or vee" },
	{ "⊕", "circled plus xor direct sum" },
	{ "⊗", "circled times tensor product" },
	{ "⊢", "proves turnstile" },
	{ "⊨", "models true" },
	{ "∴", "therefore" },
	{ "∵", "because" },
	{ "∎", "end of proof qed" },
	// arrows
	{ "→", "rightwards arrow implies maps to" },
	{ "←", "leftwards arrow" },
	{ "↔", "left right arrow" },
	{ "⇒", "rightwards double arrow implies" },
	{ "⇐", "leftwards double arrow" },
	{ "⇔", "left right double arrow if and only if iff" },
	{ "↦", "maps to" },
	// geometry
	{ "∠", "angle" },
	{ "⊥", "perpendicular up tack" },
	{ "∥", "parallel to" },
	{ "△", "triangle" },
	// brackets
	{ "⌊", "left floor" },
	{ "⌋", "right floor" },
	{ "⌈", "left ceiling" },
	{ "⌉", "right ceiling" },
	{ "⟨", "left angle bracket" },
	{ "⟩", "right angle bracket" },
	{ "‖", "double vertical line norm" },
	{ "∣", "divides" },
	{ "∤", "does not divide" },
	{ "…", "horizontal ellipsis" },
	{ "⋯", "midline horizontal ellipsis" },
	{ "⋮", "vertical ellipsis" },
	// Greek
	{ "α", "greek alpha" },
	{ "β", "greek beta" },
	{ "γ", "greek gamma" },
	{ "δ", "greek delta" },
	{ "ε", "greek epsilon" },
	{ "ζ", "greek zeta" },
	{ "η", "greek eta" },
	{ "θ", "greek theta" },
	{ "λ", "greek lambda" },
	{ "μ", "greek mu micro" },
	{ "ξ", "greek xi" },
	{ "π", "greek pi" },
	{ "ρ", "greek rho" },
	{ "σ", "greek sigma" },
	{ "τ", "greek tau" },
	{ "φ", "greek phi" },
	{ "χ", "greek chi" },
	{ "ψ", "greek psi" },
	{ "ω", "greek omega" },
	{ "Γ", "greek capital gamma" },
	{ "Δ", "greek capital delta" },
	{ "Θ", "greek capital theta" },
	{ "Λ", "greek capital lambda" },
	{ "Π", "greek capital pi" },
	{ "Σ", "greek capital sigma" },
	{ "Φ", "greek capital phi" },
	{ "Ψ", "greek capital psi" },
	{ "Ω", "greek capital omega ohm" },
	// superscripts, subscripts, fractions
	{ "⁰", "superscript zero" },
	{ "¹", "superscript one" },
	{ "²", "superscript two squared" },
	{ "³", "superscript three cubed" },
	{ "⁴", "superscript four" },
	{ "ⁿ", "superscript n" },
	{ "⁺", "superscript plus" },
	{ "⁻", "superscript minus" },
	{ "₀", "subscript zero" },
	{ "₁", "subscript one" },
	{ "₂", "subscript two" },
	{ "₃", "subscript three" },
	{ "ₙ", "subscript n" },
	{ "½", "one half fraction" },
	{ "⅓", "one third fraction" },
	{ "⅔", "two thirds fraction" },
	{ "¼", "one quarter fraction" },
	{ "¾", "three quarters fraction" },
	{ "⅛", "one eighth fraction" },
};
const int math_symbol_count = sizeof(math_symbols) / sizeof(math_symbols[0]);

const struct emoji ascii_emoticons[] = {
	{ ":-)", "smile happy smiley" },
	{ ":)", "smile happy smiley" },
	{ ";-)", "wink" },
	{ ":-D", "grin laugh big smile" },
	{ "XD", "laughing squinting" },
	{ ":-(", "sad frown" },
	{ ":'(", "crying tears" },
	{ ":-P", "tongue out cheeky" },
	{ ":-O", "surprised shocked" },
	{ ":-|", "straight face neutral" },
	{ ":-/", "skeptical unsure" },
	{ ":-*", "kiss" },
	{ ":-$", "embarrassed" },
	{ ">:-(", "angry" },
	{ "8-)", "cool sunglasses" },
	{ "O:-)", "angel innocent" },
	{ ":3", "cat face cute" },
	{ "<3", "heart love" },
	{ "</3", "broken heart" },
	{ "^_^", "happy joyful" },
	{ "^^", "happy smile" },
	{ "-_-", "annoyed unimpressed" },
	{ ">_<", "frustrated" },
	{ "o_O", "confused weird" },
	{ "O_o", "confused weird" },
	{ "T_T", "crying" },
	{ "*_*", "starstruck amazed" },
	{ "=)", "smile happy" },
	{ "\\o/", "cheering hooray yay" },
	{ "o/", "waving hello" },
	{ "\\m/", "rock on horns" },
	{ "(y)", "thumbs up like" },
	{ "(n)", "thumbs down dislike" },
	{ "<(^_^)>", "happy dance" },
	{ "(^_~)", "wink" },
	{ "(-_-)zzz", "sleeping sleepy" },
	{ "(o_o)", "staring" },
	{ "(>_<)", "frustrated" },
	{ "m(_ _)m", "bowing sorry thanks" },
	{ "<(\")", "penguin" },
	{ "<:3 )~", "mouse" },
	{ "~(_8^(I)", "homer simpson" },
	{ "@}->--", "rose flower" },
	{ "<><", "fish" },
	{ "¯\\_(ツ)_/¯", "shrug whatever" },
	{ "(╯°□°)╯︵ ┻━┻", "flip the table tableflip rage" },
	{ "┬─┬ノ( º _ ºノ)", "put the table back calm" },
	{ "( ͡° ͜ʖ ͡°)", "lenny face" },
	{ "ಠ_ಠ", "look of disapproval" },
	{ "(ノ◕ヮ◕)ノ*:･ﾟ✧", "sparkles magic excited" },
	{ "ʕ•ᴥ•ʔ", "bear" },
	{ "(づ｡◕‿‿◕｡)づ", "hug" },
	{ "ᕕ( ᐛ )ᕗ", "happy walk away" },
	{ "(☞ﾟヮﾟ)☞", "pointing you" },
	{ "(ಥ﹏ಥ)", "crying sobbing" },
};
const int ascii_emoticon_count = sizeof(ascii_emoticons) / sizeof(ascii_emoticons[0]);
