#!/usr/bin/env python3
"""Writes panel/emoji_data.c from Unicode's emoji-test.txt.

Keeps the fully-qualified emoji without their skin tone variants (the plain
one stands for them), in Unicode's order and groups, each with its name.

usage: gen-emoji.py <emoji-test.txt> > panel/emoji_data.c
(https://unicode.org/Public/emoji/latest/emoji-test.txt)
"""
import re
import sys

SKIN = set(range(0x1F3FB, 0x1F400))
GROUPS = {
    "Smileys & Emotion": "Smileys",
    "People & Body": "People",
    "Animals & Nature": "Nature",
    "Food & Drink": "Food",
    "Travel & Places": "Travel",
    "Activities": "Activities",
    "Objects": "Objects",
    "Symbols": "Symbols",
    "Flags": "Flags",
}


def c_string(text):
    out = []
    for b in text.encode("utf-8"):
        if b < 0x20 or b > 0x7e or b in (0x22, 0x5c):
            out.append("\\%03o" % b)
        else:
            out.append(chr(b))
    return '"' + "".join(out) + '"'


def main():
    source = open(sys.argv[1], encoding="utf-8").read().splitlines()
    version = next((l.split(":", 1)[1].strip() for l in source if l.startswith("# Version:")), "?")
    groups, entries, group = [], [], None
    for line in source:
        m = re.match(r"# group: (.*)", line)
        if m:
            name = m.group(1).strip()
            group = GROUPS.get(name)
            if group:
                groups.append([group, len(entries), 0])
            continue
        if not group or not line or line.startswith("#"):
            continue
        m = re.match(r"([0-9A-F ]+);\s*fully-qualified\s*#\s*\S+\s+E[\d.]+\s+(.*)", line)
        if not m:
            continue
        points = [int(p, 16) for p in m.group(1).split()]
        if SKIN & set(points):
            continue
        entries.append(("".join(chr(p) for p in points), m.group(2).strip()))
        groups[-1][2] += 1
    print("/* Generated by tools/gen-emoji.py from Unicode's emoji-test.txt, version %s." % version)
    print(" * Unicode data is under the Unicode License (https://www.unicode.org/license.txt). */")
    print('#include "emoji.h"')
    print()
    print("const struct emoji_group emoji_groups[] = {")
    for name, first, count in groups:
        print('\t{ "%s", %d, %d },' % (name, first, count))
    print("};")
    print("const int emoji_group_count = %d;" % len(groups))
    print()
    print("const struct emoji emoji_list[] = {")
    for chars, name in entries:
        print("\t{ %s, %s }," % (c_string(chars), c_string(name)))
    print("};")
    print("const int emoji_count = %d;" % len(entries))


main()
